version: 0.2

phases:
  install:
    commands:
        - echo install Mocha...
        - npm install -g mocha
  pre_build:
    commands:
      - echo installing source dependencies...
      - npm install
      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling Node.js code...
      - npm test
  post_build:
    commands:
      - echo Running Node.js
      - npm start
artifacts:
  files:
    - app.js
    - package.json
    - index.html
    - node_modules/async/*
    - node_modules/lodash/*